# Pure python solution

In [1]:
import random
import operator

from functools import reduce

shape = 10

matrix = [[[random.randint(0,9) for i in range(shape)] 
                                for j in range(shape)] 
                                for k in range(shape)]

In [2]:
#mul by shapes

# row
d1 = [[reduce(operator.mul, [matrix[__][_][___] for ___ in range(shape)], 1), _, __] 
      for __ in range(shape) for _ in range(shape)]
# col
d2 = [[reduce(operator.mul, [matrix[__][___][_] for ___ in range(shape)], 1), _, __] 
      for __ in range(shape) for _ in range(shape)]
# page - 3rd dimension
d3 = [[reduce(operator.mul, [matrix[___][__][_] for ___ in range(shape)]), _, __] 
      for __ in range(shape) for _ in range(shape)]

In [3]:
#min mul row
print [matrix[min(d1)[2]][min(d1)[1]][_] for _ in range(shape)]
#min mul col
print [matrix[min(d2)[2]][_][min(d2)[1]] for _ in range(shape)]
#min mul page
print [matrix[_][min(d3)[2]][min(d3)[1]] for _ in range(shape)]

[8, 5, 9, 9, 6, 2, 9, 5, 0, 8]
[8, 2, 4, 6, 1, 3, 0, 8, 3, 1]
[8, 1, 8, 8, 0, 8, 9, 0, 6, 2]


# NumPy solution

In [4]:
import numpy as np

shape = 10

matrix = np.random.randint(0,10, size=(shape, shape, shape))

In [5]:
d1 = matrix.prod(2)
d2 = matrix.prod(1)
d3 = matrix.prod(0)

In [6]:
# index of min 
ind1 = np.unravel_index(d1.argmin(), d1.shape)
ind2 = np.unravel_index(d2.argmin(), d2.shape)
ind3 = np.unravel_index(d3.argmin(), d3.shape)

In [7]:
print matrix[ind1[0], ind1[1], :]
print matrix[ind2[0], :, ind2[1]]
print matrix[:, ind3[0], ind3[1]]

[2 8 9 9 8 3 0 9 6 9]
[9 5 1 4 9 0 8 0 2 1]
[7 8 0 3 6 6 6 8 1 9]
